### ISSUE TITLE
Will you make Firefox compatible extension?

### ISSUE THREAD

**Issue by SleepDaemon** [razoo-choudhary/quillbot-premium#1]
The extension is only available for chrome, is it possible if you can make a firefox compatible one?

**Comment by razoo-choudhary** [comment]
@SleepDaemon We have worked out the solution for your problem 

https://addons.mozilla.org/en-US/firefox/addon/quillbot-premium/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search

**Comment by superpitzi2** [comment]
can you update the token ? it was working for couple of seconds, and than saying you need to get new one. thank you

**Comment by razoo-choudhary** [comment]
@superpitzi2 for now no word limit, standard and fluency are the only working option its because the account used to make premium has expired, updating a token means new account, as soon as I get new account I will update the token.
