### ISSUE TITLE
  "manifest_version": 2,  

### ISSUE THREAD

**Issue by Malhabib** [razoo-choudhary/quillbot-premium#8]
**Describe the bug**

Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by razoo-choudhary** [comment]
@Malhabib the manifest warning is not the issue, currently the manifest version 2.0 is still stable version so will update that only when needed.
